# Generated by Django 2.0 on 2022-12-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('userlist', models.FileField(upload_to=None, verbose_name='Members')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'verbose_name': 'Event',
            },
        ),
        migrations.AlterField(
            model_name='fields',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.Events', verbose_name='Events'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='file',
            field=models.FileField(upload_to=None, verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='headerln',
            field=models.IntegerField(verbose_name='Header line height'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='headermtop',
            field=models.IntegerField(verbose_name='Header Margin Top'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='headersize',
            field=models.IntegerField(verbose_name='Header size'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='textln',
            field=models.IntegerField(verbose_name='Text line height'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='textmtop',
            field=models.IntegerField(verbose_name='Text Margin Top'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='textsize',
            field=models.IntegerField(verbose_name='Text size'),
        ),
    ]
